### ISSUE TITLE
plot PSTHs of population as rasters/ heat maps

### ISSUE THREAD

**Issue by pavanramkumar** [KordingLab/spykes#60]
Suggestion from Lee Miller's Beer & Brainstorm:

"We often plot mean PSTHs of neurons in a population as a raster or heat map. We may sort these by 
- preferred stimulus 
- firing rate
- peak latency of PSTH"

Takeaway:

Write a new class called `PopVis()` which 
- takes a population of spike counts
- computes preferred stimuli 
- computes PSTHs
- plots them as a heat map (rows = neurons, cols = time)
- takes a `sortby` argument that sorts neurons by one of above three ways

**Comment by pavanramkumar** [comment]
I just realized that we could add another simple method to `PopVis()` which is `plot_population_PSTH()` which is basically the average of normalized PSTHs across neurons.

@timshell you've already implemented a version of this in your notebook replicating the reward figure, so you can probably adapt that code into a nice method.

**Comment by timshell** [comment]
@pavanramkumar So I kind of did that in a "hacky" way by having a base neuron, manually changing its PSTH data to represent the population, and then plotting that neuron. I did this to use the NeuroVis functionality since I don't have the population spiketimes. 

Should I:

1. do it in that "hacky" way

2. adapt the neuron plot_PSTH code to be the population_PSTH code

**Comment by pavanramkumar** [comment]
@timshell that's a great point and I think it's possible to do both without violating the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

why not just have `population_PSTH()` be a wrapper around `plot_PSTH()`? that way if we change the visual style or add more parameters in the future, it will all be in one place.

**Comment by timshell** [comment]
finished via #63
